# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode9.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/YKPhotoCircleCrop.xcworkspace -scheme YKPhotoCircleCrop-Example -sdk iphonesimulator11.4 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
