os: osx
osx_image: xcode9.4
language: objective-c
cache: cocoapods
podfile: Example/Podfile
xcode_workspace: Example/YKPhotoCircleCrop.xcworkspace
xcode_scheme: YKPhotoCircleCrop_Example
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - pod lib lint
  - set -o pipefail && xcodebuild -workspace Example/YKPhotoCircleCrop.xcworkspace -scheme YKPhotoCircleCrop_Example -sdk iphonesimulator11.4 ONLY_ACTIVE_ARCH=NO | xcpretty
